### ISSUE TITLE
证书问题

### ISSUE THREAD

**Issue by zuxue** [wannanbigpig/alipay-sdk-php#33]
需要那几个证书，试过几个，结果都是签名错误，通过支付宝官方提供的应用获取到的是两个txt文件，一个csr文件，以及自己从开放平台下载的三个证书文件

**Comment by wannanbigpig** [comment]
是否配置过证书路径（检查证书路径）或者配置证书字符串（检查证书字符串是否正确），

**Comment by wannanbigpig** [comment]
https://alipay.docs.wannanbigpig.com/kai-shi-shi-yong/config 你可以根据文档的这个配置说明看看你是否是配置参数传入有误

**Comment by wannanbigpig** [comment]
https://docs.open.alipay.com/291/105971/ 支付宝证书如何获取请参考支付宝文档，秘钥格式可以选PKCS1（非java适用）

**Comment by zuxue** [comment]
证书都下载好了，只是不知道这个private_key 和 public_key 需要的都是哪个证书。
private_key 文件只有一个，文件名是‘****_私钥.txt’ ，但是public_key 文件却有好几个，一个应用公钥，一个支付宝公钥，还一个‘****_公钥.txt’ .
还是说当前环境的域名是需要与支付宝后台配置的域名一致吗？
目前使用的是应用公钥，但是返回错误码是40002，提示验签错误，检查签名字符串或签名私钥与应用公钥是否匹配
新人第一次接入支付宝，希望大神给点指导，谢谢了！

**Comment by wannanbigpig** [comment]
```
// 配置（包含支付宝的公共配置，日志配置，http配置等）
$config = [
     // ...
    'private_key_path' => STORAGE_ROOT.'private_key.pem',
      //  'private_key' => '私钥字符串', // 和 private_key_path 二选一
    'alipay_public_Key_path' => STORAGE_ROOT.'alipay_public_key.pem',
      //  'alipay_public_Key' => '支付宝公钥字符串', // 和 alipay_public_Key_path 二选一
    // ...
```
私钥是你自己生成，与你上传到支付宝的公钥时一对的。公钥是你在支付宝下载的支付宝公钥用于返回值检验的
